channels:
- https://packages.qiime2.org/qiime2/2024.5/amplicon/passed
- https://packages.qiime2.org/qiime2/2024.10/amplicon/passed
- conda-forge
- bioconda
- defaults
dependencies:
  - qiime2-amplicon
  - q2-stats
  - pip
  - pip:
    - q2_vizard@git+https://github.com/qiime2/q2-vizard.git@dev
